package dev.synthara.research.workflow;

import dev.synthara.research.records.ExecutiveSummary;
import dev.synthara.research.records.MarkdownReport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.stream.Collectors;

@Component
public class ReportGenerationStage {
    private static final Logger log = LoggerFactory.getLogger(ReportGenerationStage.class);
    private final OpenRouterLlmService llmService;

    public ReportGenerationStage(OpenRouterLlmService llmService) {
        this.llmService = llmService;
    }

    public MarkdownReport generate(ExecutiveSummary summary) {
        log.info("Generating dynamic Markdown Report for topic: {}", summary.topic());
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy"));

        String summaryDataText = String.format(
            "Topic: %s\n" +
            "Summary: %s\n" +
            "Major Findings:\n%s\n" +
            "Strategic Insights:\n%s\n" +
            "Risks:\n%s\n" +
            "Opportunities:\n%s\n" +
            "Outlook: %s\n" +
            "Confidence Score: %d/100",
            summary.topic(),
            summary.summary(),
            summary.majorFindings().stream().map(f -> "- " + f).collect(Collectors.joining("\n")),
            summary.strategicInsights().stream().map(i -> "- " + i).collect(Collectors.joining("\n")),
            summary.risks().stream().map(r -> "- " + r).collect(Collectors.joining("\n")),
            summary.opportunities().stream().map(o -> "- " + o).collect(Collectors.joining("\n")),
            summary.futureOutlook(),
            summary.confidenceScore()
        );

        String prompt = String.format(
            "You are a principal market research director. Based on the synthesized executive briefing below for the topic '%s', write a comprehensive, publication-quality Markdown Research Report.\n\n" +
            "Briefing Data:\n%s\n\n" +
            "The report MUST have the following sections:\n" +
            "1. A beautiful headline: '# %s'\n" +
            "2. Document metadata block: '**Research Report** | %s'\n" +
            "3. '## Executive Summary'\n" +
            "4. '## Market Overview' (write 2 detailed, professional paragraphs discussing the actual landscape of this topic)\n" +
            "5. '## Key Players & Competitors' (briefly discuss who the main players are and provide a beautifully formatted Markdown table comparing them on 3-4 feature dimensions)\n" +
            "6. '## SWOT Analysis' (structured under bulleted lists of Strengths, Weaknesses, Opportunities, and Threats)\n" +
            "7. '## Key Trends' (a numbered list of 4-5 major trends driving the future of this domain)\n" +
            "8. '## Conclusion' (include a summary of the future outlook)\n" +
            "9. End with: '**Confidence Score: %d/100**'\n" +
            "10. Bottom signature: '---\\n*Generated by Synthara Research Analyst on %s*'\n\n" +
            "Return ONLY the markdown document, with no introductory remarks or other text.",
            summary.topic(), summaryDataText, summary.topic(), date, summary.confidenceScore(), date
        );

        try {
            log.info("Querying LLM to write the comprehensive Markdown report...");
            String reportContent = llmService.call(prompt);
            if (reportContent == null || reportContent.isBlank()) {
                throw new RuntimeException("LLM returned empty response");
            }
            reportContent = reportContent.trim();

            if (reportContent.startsWith("```")) {
                reportContent = reportContent.replaceAll("^```markdown\\s*", "").replaceAll("^```\\s*", "").replaceAll("\\s*```$", "");
            }

            return new MarkdownReport(
                summary.topic(),
                summary.topic() + " - Research Report",
                "",
                summary.summary(),
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                reportContent
            );

        } catch (Exception e) {
            log.error("Failed to generate dynamic markdown report, using local construction: {}", e.getMessage());
            
            // Standard fallback building
            var sb = new StringBuilder();
            sb.append("# ").append(summary.topic()).append("\n\n");
            sb.append("**Research Report** | ").append(date).append("\n\n---\n\n");
            sb.append("## Executive Summary\n\n").append(summary.summary()).append("\n\n");
            sb.append("### Major Findings\n\n");
            summary.majorFindings().forEach(f -> sb.append("- ").append(f).append("\n"));
            sb.append("\n### Strategic Insights\n\n");
            summary.strategicInsights().forEach(i -> sb.append("- ").append(i).append("\n"));
            sb.append("\n## Market Overview\n\nThe ").append(summary.topic().toLowerCase()).append(" is undergoing rapid technological and market integration.\n\n");
            sb.append("## SWOT Analysis\n\n");
            sb.append("Strengths: Growing adoption and strong capabilities.\n\n");
            sb.append("Weaknesses: Compliance and integration barriers.\n\n");
            sb.append("Opportunities: High-growth vertical segments.\n\n");
            sb.append("Threats: Market consolidation and infrastructural dependencies.\n\n");
            sb.append("## Conclusion\n\n").append(summary.futureOutlook()).append("\n\n");
            sb.append("**Confidence Score: ").append(summary.confidenceScore()).append("/100**\n\n");
            sb.append("---\n*Generated by Synthara Research Analyst on ").append(date).append("*\n");

            return new MarkdownReport(
                summary.topic(),
                summary.topic() + " - Research Report",
                "",
                summary.summary(),
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                sb.toString()
            );
        }
    }
}
