package dev.synthara.research.workflow;

import dev.synthara.research.records.ExecutiveSummary;
import dev.synthara.research.records.MarkdownReport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.stream.Collectors;

@Component
public class ReportGenerationStage {
    private static final Logger log = LoggerFactory.getLogger(ReportGenerationStage.class);
    private final OpenRouterLlmService llmService;

    public ReportGenerationStage(OpenRouterLlmService llmService) {
        this.llmService = llmService;
    }

    public MarkdownReport generate(ExecutiveSummary summary) {
        log.info("Generating dynamic Markdown Report for topic: {}", summary.topic());
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy"));

        String summaryDataText = String.format(
            "Topic: %s\n" +
            "Summary: %s\n" +
            "Major Findings:\n%s\n" +
            "Strategic Insights:\n%s\n" +
            "Risks:\n%s\n" +
            "Opportunities:\n%s\n" +
            "Outlook: %s\n" +
            "Confidence Score: %d/100",
            summary.topic(),
            summary.summary(),
            summary.majorFindings().stream().map(f -> "- " + f).collect(Collectors.joining("\n")),
            summary.strategicInsights().stream().map(i -> "- " + i).collect(Collectors.joining("\n")),
            summary.risks().stream().map(r -> "- " + r).collect(Collectors.joining("\n")),
            summary.opportunities().stream().map(o -> "- " + o).collect(Collectors.joining("\n")),
            summary.futureOutlook(),
            summary.confidenceScore()
        );

        String prompt = String.format(
            "You are a principal market research director writing for a Fortune 500 board of directors. " +
            "Based on the synthesized executive briefing below for the topic '%s', write a COMPREHENSIVE, DETAILED, " +
            "publication-quality Markdown Research Report that is AT LEAST 1200 words long (approximately 2-3 printed pages).\n\n" +
            "Briefing Data:\n%s\n\n" +
            "CRITICAL REQUIREMENTS — each section must be fully developed with real depth:\n\n" +
            "1. Headline: '# %s'\n" +
            "2. Metadata: '**Research Report** | %s'\n" +
            "3. '## Executive Summary' — Write 4-5 substantive sentences covering the state of the domain, key drivers, " +
            "investment climate, and strategic imperative.\n" +
            "4. '## Market Overview' — Write AT LEAST 3 full paragraphs (200+ words total). Cover: current market size & growth, " +
            "key drivers, geographic hotspots, recent developments, and investment/funding trends.\n" +
            "5. '## Technology & Innovation Landscape' — 2 paragraphs on the underlying tech stack, emerging innovations, " +
            "R&D activity, and any patent or standards activity in this space.\n" +
            "6. '## Key Players & Competitive Landscape' — 2 introductory paragraphs discussing the competitive dynamics, " +
            "market concentration, and moat analysis. Then include a Markdown comparison table.\n" +
            "   STRICT TABLE FORMATTING RULES (violations will break the document):\n" +
            "   - The table MUST be preceded by exactly ONE blank line after the last paragraph.\n" +
            "   - Row 1: header row with column names separated by | characters.\n" +
            "   - Row 2: separator row using |---|---|---| format.\n" +
            "   - Each subsequent row is ONE line — do NOT split a row across multiple lines.\n" +
            "   - Cell content must NOT contain newlines, <br> tags, or hard line breaks.\n" +
            "   - Keep cell content concise (max 15 words per cell) — no full paragraphs inside cells.\n" +
            "   - The table MUST be followed by exactly ONE blank line before the next section.\n" +
            "   - Include at least 5 named real-world players and 5 column dimensions.\n" +
            "7. '## SWOT Analysis' — For each quadrant (Strengths, Weaknesses, Opportunities, Threats) provide at least " +
            "4 bullet points. Each bullet must be 1-2 sentences with specific evidence or context.\n" +
            "8. '## Key Trends & Future Outlook' — A numbered list of AT LEAST 6 major trends, each with 2-3 sentences " +
            "of explanation covering why the trend matters and what it implies for stakeholders.\n" +
            "9. '## Strategic Recommendations' — 4-5 actionable recommendations for decision-makers, each as a bold " +
            "header with 2 sentences of supporting rationale.\n" +
            "10. '## Conclusion' — A 3-4 sentence forward-looking synthesis.\n" +
            "11. '**Confidence Score: %d/100**'\n" +
            "12. '---\\n*Generated by Synthara Research Analyst on %s*'\n\n" +
            "Do NOT truncate any section. Be thorough, specific, and data-rich. " +
            "Return ONLY the markdown document with no preamble, disclaimers, or closing remarks outside the document.",
            summary.topic(), summaryDataText, summary.topic(), date, summary.confidenceScore(), date
        );

        try {
            log.info("Querying LLM to write the comprehensive Markdown report...");
            String reportContent = llmService.call(prompt);
            if (reportContent == null || reportContent.isBlank()) {
                throw new RuntimeException("LLM returned empty response");
            }
            reportContent = reportContent.trim();

            // Strip markdown code fences if the LLM wrapped the output
            if (reportContent.startsWith("```")) {
                reportContent = reportContent.replaceAll("^```markdown\\s*", "").replaceAll("^```\\s*", "").replaceAll("\\s*```$", "");
            }

            // Post-process: ensure every table row (lines starting with |) is preceded by a blank line
            // This catches cases where the LLM attaches a table row directly to paragraph text
            String[] lines = reportContent.split("\n");
            StringBuilder fixed = new StringBuilder();
            for (int i = 0; i < lines.length; i++) {
                String line = lines[i];
                boolean isTableRow = line.trim().startsWith("|");
                boolean prevIsTableRow = i > 0 && lines[i - 1].trim().startsWith("|");
                boolean prevIsBlank = i > 0 && lines[i - 1].trim().isEmpty();
                // Insert blank line before a table block starts (first table row not preceded by blank)
                if (isTableRow && !prevIsTableRow && !prevIsBlank && i > 0) {
                    fixed.append("\n");
                }
                // Insert blank line after a table block ends (first non-table row not preceded by blank)
                if (!isTableRow && prevIsTableRow && !prevIsBlank) {
                    fixed.append("\n");
                }
                fixed.append(line).append("\n");
            }
            reportContent = fixed.toString().trim();

            return new MarkdownReport(
                summary.topic(),
                summary.topic() + " - Research Report",
                "",
                summary.summary(),
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                reportContent
            );

        } catch (Exception e) {
            log.error("Failed to generate dynamic markdown report, using local construction: {}", e.getMessage());
            
            // Standard fallback building
            var sb = new StringBuilder();
            sb.append("# ").append(summary.topic()).append("\n\n");
            sb.append("**Research Report** | ").append(date).append("\n\n---\n\n");
            sb.append("## Executive Summary\n\n").append(summary.summary()).append("\n\n");
            sb.append("### Major Findings\n\n");
            summary.majorFindings().forEach(f -> sb.append("- ").append(f).append("\n"));
            sb.append("\n### Strategic Insights\n\n");
            summary.strategicInsights().forEach(i -> sb.append("- ").append(i).append("\n"));
            sb.append("\n## Market Overview\n\nThe ").append(summary.topic().toLowerCase()).append(" is undergoing rapid technological and market integration.\n\n");
            sb.append("## SWOT Analysis\n\n");
            sb.append("Strengths: Growing adoption and strong capabilities.\n\n");
            sb.append("Weaknesses: Compliance and integration barriers.\n\n");
            sb.append("Opportunities: High-growth vertical segments.\n\n");
            sb.append("Threats: Market consolidation and infrastructural dependencies.\n\n");
            sb.append("## Conclusion\n\n").append(summary.futureOutlook()).append("\n\n");
            sb.append("**Confidence Score: ").append(summary.confidenceScore()).append("/100**\n\n");
            sb.append("---\n*Generated by Synthara Research Analyst on ").append(date).append("*\n");

            return new MarkdownReport(
                summary.topic(),
                summary.topic() + " - Research Report",
                "",
                summary.summary(),
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                sb.toString()
            );
        }
    }
}
