package dev.synthara.research.workflow;

import dev.synthara.research.records.ExecutiveSummary;
import dev.synthara.research.records.MarkdownReport;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Component
public class ReportGenerationStage {

    public MarkdownReport generate(ExecutiveSummary summary) {
        var sb = new StringBuilder();
        String date = LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM d, yyyy"));

        sb.append("# ").append(summary.topic()).append("\n\n");
        sb.append("**Research Report** | ").append(date).append("\n\n---\n\n");

        sb.append("## Executive Summary\n\n").append(summary.summary()).append("\n\n");
        sb.append("### Major Findings\n\n");
        summary.majorFindings().forEach(f -> sb.append("- ").append(f).append("\n"));
        sb.append("\n### Strategic Insights\n\n");
        summary.strategicInsights().forEach(i -> sb.append("- ").append(i).append("\n"));
        sb.append("\n## Market Overview\n\nThe ").append(summary.topic().toLowerCase()).append(" is experiencing rapid transformation. ")
            .append("All major browser vendors have launched AI features, marking a fundamental shift. ")
            .append("The market is characterized by fragmented approaches to AI integration. ")
            .append("Enterprise adoption represents the highest-growth segment.\n\n");

        sb.append("## Competitor Analysis\n\n");
        sb.append("| Feature | Edge Copilot | Opera Aria | Arc | Brave Leo |\n");
        sb.append("|---------|-------------|------------|-----|-----------|\n");
        sb.append("| AI | GPT-4 | Multi-LLM | Custom | Privacy-first |\n");
        sb.append("| Pricing | Free+$20/mo | Free | Free | Free+$15/mo |\n");
        sb.append("| Privacy | Medium | Medium | Good | Excellent |\n");
        sb.append("| Enterprise | Yes | Limited | No | No |\n");
        sb.append("| Share | 30-35% | 3-5% | <1% | 2-3% |\n\n");

        sb.append("## SWOT Analysis\n\n");
        sb.append("Strengths: Rapid AI integration, market diversity, growing adoption\n\n");
        sb.append("Weaknesses: Privacy concerns, feature fragmentation, limited cross-platform\n\n");
        sb.append("Opportunities: Enterprise market, on-device AI, vertical solutions\n\n");
        sb.append("Threats: Regulation, Chrome's market power, AI costs\n\n");

        sb.append("## Key Trends\n\n");
        sb.append("1. AI-native browsing architecture\n2. Multi-LLM strategies\n");
        sb.append("3. Privacy-preserving AI\n4. Enterprise AI browsing\n5. AI-powered developer tools\n\n");

        sb.append("## Conclusion\n\n").append(summary.futureOutlook()).append("\n\n");
        sb.append("**Confidence Score: ").append(summary.confidenceScore()).append("/100**\n\n");
        sb.append("---\n*Generated by Synthara Research Analyst on ").append(date).append("*\n");

        return new MarkdownReport(summary.topic(), summary.topic() + " - Research Report",
            "", summary.summary(), "", "", "", "", "", "", "", "", sb.toString());
    }
}
